mutation Login($email: String!, $password: String!) {
    login(email:$email,password:$password) {
        access_token
        expires_in
        user {
            id
            email
            name
            created_at
            updated_at
        }
    }
}
